周一:
  启用: true
  name: 自定义  
  开始时间: 9
  持续小时数: 13
  自定义:
    - 29072
周二:
  启用: true
  name: 自定义  
  开始时间: 9
  持续小时数: 13
  自定义:
    - 29072
周三:
  启用: true
  name: 自定义  
  开始时间: 9
  持续小时数: 13
  自定义:
    - 29072
周四:
  启用: true
  name: 自定义  
  开始时间: 9
  持续小时数: 13
  自定义:
    - 29072
周五:
  启用: true
  name: 自定义  
  开始时间: 9
  持续小时数: 13
  自定义:
    - 29072
周六:
  启用: true
  name: 自定义  
  开始时间: 9
  持续小时数: 13
  自定义:
    - 29072
周日:
  启用: true
  name: 自定义  
  开始时间: 9
  持续小时数: 13
  自定义:
    - 29072
